describe("Testing form", function () {
    beforeEach(function() {
        cy.visit("http://localhost:3000/pizza")
    })
    it("Testing inputs on form", function () {
        cy.get('input[name="name"]')
            .type('Tanner')
            .should('have.value', 'Tanner')
        cy.get('select')
            .select('Jumbo')
            .should('have.value', 'Jumbo')
        cy.get('input[name="pepperoni"]')
            .check()
            .should('be.checked')
        cy.get('input[name="sausage"]')
            .check()
            .should('be.checked')
        cy.get('input[name="onions"]')
            .check()
            .should('be.checked')
        cy.get('textarea')
            .type('GIVE ME EXTRA CHEESE')
            .should('have.value', 'GIVE ME EXTRA CHEESE')
        cy.get('form')
            .submit()
    })
})